# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 864dfc5a0a4f6e0af3ba5e02a979119c8135f68174cc359af5ccdee10f716a02d6f8d964271808fb21a6e411ec9b3d6a512407529433803848cc296a464437ff

test:
  secret_key_base: 4db86696137483ab2c5edd67e30a42f38518f1c58f3ba98b348cb60e81373bd43b0bac1b9b1e6b46a4b82bcb819db7cda0c6df7035074d225919ec1a615bc4e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
